In [2]:
import numpy as np

print("NumPy version:", np.__version__)


NumPy version: 2.3.2


### Creating array from list

In [5]:
arr1 = np.array([1,2,3])
print("1D array is: ", arr1)

arr2 = np.array([[1,2,3],[4,5,6]])
print("2D array is: \n", arr2)



1D array is:  [1 2 3]
2D array is: 
 [[1 2 3]
 [4 5 6]]



### List vs numpy array

In [7]:
py_list = [1,2,3]
print("Python list multiplication \n", py_list*2)

np_array = np.array([1,2,3])
print("Python array multiplication \n", np_array*2)

Python list multiplication 
 [1, 2, 3, 1, 2, 3]
Python array multiplication 
 [2 4 6]


###Creating array from scratch

In [12]:
Zeros = np.zeros((3,4))
print("zeros array: \n", Zeros)

ones = np.ones((2,3))
print("zeros array: \n", ones)
 
full = np.full((2,2), 7)
print("full array: \n", full)

random = np.random.random((2,3))
print("Random array: \n", random)

sequence = np.arange(0, 10, 2)
print("Sequence array: \n", sequence)



zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
zeros array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
Random array: 
 [[0.8524237  0.53463249 0.55246233]
 [0.61117982 0.75327824 0.49379429]]
Sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [18]:
vector = np.array([1,2,3])
print("Vector: \n", vector)

matrix = np.array([[1,2,3],
                  [4,5,6]])
print("Matrix: \n",matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print("tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [21]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)
print("Shape ", arr.shape)
print("Dimensiosn ", arr.ndim)
print("Size ", arr.size)
print("Data types ", arr.dtype)

[[1 2 3]
 [4 5 6]]
Shape  (2, 3)
Dimensiosn  2
Size  6
Data types  int64


### Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original array \n", arr)

reshaped = arr.reshape((4,3))
print("Reshaped array \n", reshaped)

flattend = reshaped.flatten()
print("Flattend array \n", flattend)

'''returns view, instead of copy'''
raveled = reshaped.ravel()
print("Raveled array \n", raveled)

'''transpose'''
transpose = reshaped.T
print("Transposed array: \n", transpose)


Original array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Flattend array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array: 
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
