### Numpy Array Operations 

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing: \n", arr[2:7])
print("With steps: \n", arr[1:8:2])
print("Negative Indexing", arr[-3])


Basic slicing: 
 [3 4 5 6 7]
With steps: 
 [2 4 6 8]
Negative Indexing 8


In [6]:
arr_2d = np.array([[1,2,3],
                  [4,5,6]])
print("Specific element: \n", arr_2d[1,2])
print("Entire row: \n", arr_2d[1])
print("Entire coloumn:  \n", arr_2d[:,1])

Specific element: 
 6
Entire row: 
 [4 5 6]
Entire coloumn:  
 [2 5]


### Sorting

In [8]:
unsorted = np.array([8,3,66,72,41,94,100,86,52,6,49])
print("Sorted array \n", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,6], [1,5], [9,3]])
print("Sorted 2D array by columm \n", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by row \n", np.sort(arr_2d_unsorted, axis=1))

Sorted array 
 [  3   6   8  41  49  52  66  72  86  94 100]
Sorted 2D array by columm 
 [[1 3]
 [3 5]
 [9 6]]
Sorted 2D array by row 
 [[3 6]
 [1 5]
 [3 9]]


### Filter

In [9]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = numbers[numbers%2==0]
print("Even number: \n",even_num)
odd_num = numbers[numbers%2 != 0]
print("Odd numbers: \n", odd_num)


Even number: 
 [ 2  4  6  8 10]
Odd numbers: 
 [1 3 5 7 9]


### Filter with mask 


In [10]:
mask = numbers > 3
print("Number greater than 3 \n", numbers[mask])

Number greater than 3 
 [ 4  5  6  7  8  9 10]


### Fancing indexing vs np.where()

In [11]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 7)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([7, 8, 9]),)
NP where [ 8  9 10]


In [ ]:
conditions_array = np.where(numbers>5, numbers*4, numbers)
print(conditions_array)

"""Similar to 
if(numbers>5){
numbers*4}
else{numbers
}""" 


[ 1  2  3  4  5 24 28 32 36 40]


'Similar to \nif(numbers>5){\nnumbers*4}\nelse{numbers\n}'

In [15]:
conditions_array2 = np.where(numbers>5,"true", "false")
print(conditions_array2)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding or removing data

In [17]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr1 + arr2 
print(combined)
concatenate = np.concatenate((arr1, arr2))
print(concatenate)


[5 7 9]
[1 2 3 4 5 6]


### array compatibility

In [21]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility shapes", a.shape == b.shape == c.shape)

Compatibility shapes True


In [26]:
original = np.array([[1,2], [3,4]])
new_row = np.array([5,6])
with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)
new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [28]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print(deleted)


[1 2 4 5]
